### ISSUE TITLE
Firmware for Board 1.0

### ISSUE THREAD

**Issue by kri5** [trinamic/TRAMS#1]
I recently got a TRAMS board 1.0, and i'd like to know which firmware version, and which documentation i should refer to?

**Comment by trinamiclj** [comment]
Dear kri5,

The FW and documentation for HW version 0.93 are valid for HW version 1.0 as well. There was no change of the HW itself, we only changed the silkscreen from HW version 0.93 to 1.0.

Hope this answers your question.
