### ISSUE TITLE
Heatbed not heating

### ISSUE THREAD

**Issue by kri5** [trinamic/TRAMS#3]
I have properly wired up the heatbead to the TRAMS board, but it does not heat when i set a temperature to heat to. It's pretty similar to the hotend, but the hottend workds properly.

Any ideas?

**Comment by kri5** [comment]
It seems that the fuse is blowned up, and i just looked at the documentation, it seems that for the heatbed the fuse was a t10a 250v, but in the package i received from digikey, i got only f5a 250v. is it expected to have only f5a or is it necessary to have a t10a for the heatbed?

**Comment by kri5** [comment]
Replaced the fuse by a t10a and seems to works so far, so not software related.
Closing the issue.

**Comment by trinamiclj** [comment]
Thanks for sharing!
